"Resource/UI/HudAccountPanel.res"
{
	"CHudAccountPanel"
	{
		"delta_item_x"			"724"
		"delta_item_start_y"	"382"
		"delta_item_end_y"		"382"
		"PositiveColor"			"0 255 0 255"
		"NegativeColor"			"255 0 0 255"
		"delta_lifetime"		"1.5"
		"delta_item_font"		"HudFontMediumSmallBold"
	}
	
	"AccountBG"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"AccountBG"
		"xpos"			"c316"
		"ypos"			"344"
		"zpos"			"0"
		"wide"			"100"
		"tall"			"100"
		"visible"		"1"
		"enabled"		"1"
		"image"			"../hud/meters/top/top"
		"scaleImage"	"1"
	}
	"AccountBGContour"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"AccountBGContour"
		"pin_to_sibling" "AccountBG"
		"xpos"			"-3"
		"ypos"			"-3"
		"zpos"			"-1"
		"wide"			"100"
		"tall"			"100"
		"visible"		"1"
		"enabled"		"1"
		"image"			"resource/svgs/top_meter/top_meter.svg"
		"drawcolor"		"TanLight"
		"scaleImage"	"1"
	}

	"MetalIcon"	
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"MetalIcon"
		"pin_to_sibling"	"AccountBG"
		"xpos"			"-55"
		"ypos"			"-39"
		"zpos"			"10"
		"wide"			"30"
		"tall"			"30"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"	
		"image"			"resource/svgs/meters/ico_metal.svg"
	}
	
	"AccountValue"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AccountValue"
		"pin_to_sibling"	"AccountBG"
		"xpos"			"-4"
		"ypos"			"-36"
		"zpos"			"2"
		"wide"			"70"
		"tall"			"26"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"%metal%"
		"textAlignment"	"center"
		"font"			"HudFontMediumBold"
		"fgcolor"		"TanLight"
	}
	
	"AccountValueOutline"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AccountValueOutline"
		"pin_to_sibling"	"AccountValue"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"70"
		"tall"			"26"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%metal%"
		"textAlignment"	"center"	
		"font"			"HudFontMediumBoldOutline"
		"fgcolor"		"ContourDark"
	}
}
