"Resource/UI/HudAmmoWeapons.res"
{
	"HudWeaponAmmoBG"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"HudWeaponAmmoBG"
		"xpos"			"c300"
		"ypos"			"380"
		"zpos"			"1"
		"wide"			"100"
		"tall"			"100"
		"visible"		"1"
		"enabled"		"1"
		"image"			"../hud/ammo/ammo_neu"
		"scaleImage"	"1"	
		"teambg_2"		"../hud/ammo/ammo_red"
		"teambg_3"		"../hud/ammo/ammo_blu"
		"teambg_4"		"../hud/ammo/ammo_grn"
		"teambg_5"		"../hud/ammo/ammo_ylw"
	}
	
	"HudWeaponAmmoCounterBG"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"HudWeaponAmmoCounterBG"
		"xpos"			"c252"
		"ypos"			"330"
		"zpos"			"1"
		"wide"			"100"
		"tall"			"100"
		"visible"		"1"
		"enabled"		"1"
		"image"			"../hud/ammo/ammo_counter_neu"
		"scaleImage"	"1"	
		"teambg_2"		"../hud/ammo/ammo_counter_red"
		"teambg_3"		"../hud/ammo/ammo_counter_blu"
		"teambg_4"		"../hud/ammo/ammo_counter_grn"
		"teambg_5"		"../hud/ammo/ammo_counter_ylw"
	}
	
	"HudWeaponAmmoCounterBGContour"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"HudWeaponAmmoCounterBGContour"
		"pin_to_sibling"	"HudWeaponAmmoCounterBG"
		"xpos"			"-4"
		"ypos"			"-4"
		"zpos"			"0"
		"wide"			"100"
		"tall"			"100"
		"visible"		"1"
		"enabled"		"1"
		"image"			"resource/svgs/ammo/ammo_counter_mask.svg"
		"drawcolor" 	"TanLight"
		"scaleImage"	"1"	
	}
	
	"HudWeaponAmmoBGContour"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"HudWeaponAmmoBGContour"
		"pin_to_sibling"	"HudWeaponAmmoBG"
		"xpos"			"-4"
		"ypos"			"-4"
		"zpos"			"0"
		"wide"			"100"
		"tall"			"100"
		"visible"		"1"
		"enabled"		"1"
		"image"			"resource/svgs/ammo/ammo_mask.svg"
		"drawcolor" 	"TanLight"
		"scaleImage"	"1"	
	}
	
	"HudWeaponAmmoIcon"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"HudWeaponAmmoIcon"
		"pin_to_sibling"	"HudWeaponAmmoBG"
		"xpos"			"11"
		"ypos"			"27"
		"zpos"			"4"
		"wide"			"55"
		"tall"			"55"
		"visible"		"1"
		"enabled"		"1"
		"image"			"resource/svgs/ammo/ammo_icon_mask.svg"
		"drawcolor" 	"DropShadow"
		"alpha"			"127.5"
		"scaleImage"	"1"	
	}

	"HudWeaponLowAmmoImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"HudWeaponLowAmmoImage"
		"xpos"			"9999"
		"ypos"			"9999"
		"zpos"			"0"
		"wide"			"0"
		"tall"			"0"
		"visible"		"0"
		"enabled"		"0"
		"image"			""
		"scaleImage"	"1"
	}

	"LowAmmoWarning"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"LowAmmoWarning"
		"xpos"			"c235"
		"ypos"			"346"
		"zpos"			"0"
		"wide"			"60"
		"tall"			"60"
		"visible"		"1"
		"enabled"		"1"
		"alpha"			"0"
		"image"			"../hud/warnings/low_ammo"
		"scaleImage"	"1"
	}
	
	"HudWeaponAmmoBGMedicCharge"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"HudWeaponAmmoBGMedicCharge"
		"xpos"			"c300"
		"ypos"			"380"
		"zpos"			"1"
		"wide"			"100"
		"tall"			"100"
		"visible"		"1"
		"enabled"		"1"
		"image"			"../hud/ammo/ammo_neu"
		"scaleImage"	"1"	
		"teambg_2"		"../hud/ammo/ammo_red"
		"teambg_3"		"../hud/ammo/ammo_blu"
		"teambg_4"		"../hud/ammo/ammo_grn"
		"teambg_5"		"../hud/ammo/ammo_ylw"
	}
	
	"HudWeaponLowAmmoImageMedicCharge"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"HudWeaponLowAmmoImageMedicCharge"
		"xpos"			"9999"
		"ypos"			"9999"
		"zpos"			"0"
		"wide"			"0"
		"tall"			"0"
		"visible"		"0"
		"enabled"		"0"
		"image"			""
		"scaleImage"	"1"
	}
	
	"WeaponBucket"
	{
		"ControlName"		"CBitmapImagePanel"
		"fieldName"			"WeaponBucket"
		"xpos"				"c307"
		"ypos"				"386"
		"zpos"				"5"
		"wide"				"90"
		"tall"				"90"
		"visible"			"0"
		"enabled"			"1"
		"scaleImage"		"1"
	}
	
	"AmmoInClip"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInClip"
		"font"			"HudFontMediumBold"
		"fgcolor"		"TanLight"
		"xpos"			"c193"
		"ypos"			"359"
		"zpos"			"7"
		"wide"			"105"
		"tall"			"40"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"east"		
		"labelText"		"%Ammo%"
		"dropshadow_override"		"1"
		"dropshadowoffset"	"3"
	}
	
	"AmmoInReserve"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInReserve"
		"font"			"HudFontSmallBold"
		"fgcolor"		"TanLight"
		"xpos"			"c302"
		"ypos"			"360"
		"zpos"			"7"
		"wide"			"105"
		"tall"			"40"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"west"
		"labelText"		"%AmmoInReserve%"
		"dropshadow_override"		"1"
		"dropshadowoffset"	"2"
	}
	
	"AmmoNoClip"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoNoClip"
		"font"			"HudFontMediumBold"
		"fgcolor"		"TanLight"
		"xpos"			"c250"
		"ypos"			"360"
		"zpos"			"7"
		"wide"			"105"
		"tall"			"40"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"center"		
		"labelText"		"%Ammo%"
		"dropshadow_override"		"1"
		"dropshadowoffset"	"3"
	}
}
