"Resource/UI/HudObjectiveTimePanel.res"
{	
	"TimePanelBG"
	{
		"ControlName"	"ScalableImagePanel"
		"fieldName"		"TimePanelBG"
		"xpos"			"17"
		"ypos"			"-20"
		"zpos"			"2"
		"wide"			"71"
		"tall"			"71"
		"visible"		"1"
		"enabled"		"1"
		"image"			"../hud/objectives_timepanel_black_bg"
		"scaleImage"		"1"
	}
	
	"TimePanelBGContour"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"TimePanelBGContour"
		"pin_to_sibling"	"TimePanelBG"
		"xpos"			"0"
		"ypos"			"-4"
		"zpos"			"1"
		"wide"			"71"
		"tall"			"71"
		"visible"		"1"
		"enabled"		"1"
		"image"				"../hud/timer/timer_contour"
		"scaleImage"		"1"
	}

	"TimePanelProgressBar"
	{
		"ControlName"		"CTFProgressBar"
		"fieldName"			"TimePanelProgressBar"
		"xpos"				"65"
		"ypos"				"6"
		"zpos"				"4"	
		"wide"				"20"
		"tall"				"20"
		"visible"			"1"
		"enabled"			"1"
		"scaleImage"		"1"
		"image"				"../hud/objectives_timepanel_progressbar_shadow"
		"color_active"		"TanLight"
		"color_inactive"	"TimerProgress.InActive"
		"color_warning"		"TimerProgress.Warning"
		"percent_warning"	"0.75"
		"drawcolor"			"0 0 0 0"
		
		"dropshadow"		"1"
		"dropshadowresize"	"0"
	}
	
	"TimePanelProgressBarShadow"
	{
		"ControlName"		"CTFProgressBar"
		"fieldName"			"TimePanelProgressBarShadow"
		"pin_to_sibling" "TimePanelProgressBar"
		"xpos"				"-2"
		"ypos"				"-2"
		"zpos"				"3"	
		"wide"				"20"
		"tall"				"20"
		"visible"			"1"
		"enabled"			"1"
		"scaleImage"		"1"
		"image"				"../hud/objectives_timepanel_progressbar_shadow"
		"color_active"		"ContourDark"
		"color_inactive"	"ContourDark"
		"color_warning"		"ContourDark"
		"drawcolor"			"0 0 0 0"
	}
	
	
	"WaitingForPlayersLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"WaitingForPlayersLabel"
		"xpos"			"12"
		"ypos"			"31"
		"ypos_minmode"	"30"
		"zpos"			"5"
		"wide"			"78"
		"tall"			"20"
		"tall_minmode"	"20"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"#game_WaitingForPlayers"
		"textAlignment"	"center"
		"font"			"HudFontSmallestBold"
		"dropshadow"	"1"
	}
	
	"WaitingForPlayersBG"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"WaitingForPlayersBG"
		"xpos"			"12"
		"ypos"			"29"
		"ypos_minmode"	"28"
		"zpos"			"1"
		"wide"			"78"
		"tall"			"21"
		"tall_minmode"	"21"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../hud/mid_meter"
		"scaleImage"	"1"
	}
	
	"OvertimeLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"OvertimeLabel"
		"xpos"			"12"
		"ypos"			"31"
		"ypos_minmode"	"30"
		"zpos"			"5"
		"wide"			"78"
		"tall"			"20"
		"tall_minmode"	"20"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"#game_Overtime"
		"textAlignment"	"center"
		"font"			"HudFontSmallestBold"
		"dropshadow"	"1"
	}
	
	"OvertimeBG"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"OvertimeBG"
		"xpos"			"12"
		"ypos"			"29"
		"ypos_minmode"	"28"
		"zpos"			"1"
		"wide"			"78"
		"tall"			"21"
		"tall_minmode"	"21"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../hud/mid_meter"
		"scaleImage"	"1"
	}
	
	"SuddenDeathLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"SuddenDeathLabel"
		"xpos"			"6"
		"ypos"			"31"
		"ypos_minmode"	"30"
		"zpos"			"5"
		"wide"			"90"
		"tall"			"20"
		"tall_minmode"	"20"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"#game_SuddenDeath"
		"textAlignment"	"center"
		"font"			"HudFontSmallestBold"
		"dropshadow"	"1"
	}
	
	"SuddenDeathBG"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"SuddenDeathBG"
		"xpos"			"0"
		"ypos"			"-15"
		"zpos"			"1"
		"wide"			"100"
		"tall"			"110"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../hud/mid_meter"
		"scaleImage"	"1"
	}
	
	"SetupLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"SetupLabel"
		"xpos"			"12"
		"ypos"			"31"
		"ypos_minmode"	"30"
		"zpos"			"5"
		"wide"			"78"
		"tall"			"20"
		"tall_minmode"	"20"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"#game_Setup"
		"textAlignment"	"center"
		"font"			"HudFontSmallestBold"
		"dropshadow"	"1"
	}	
	
	"SetupBG"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"SetupBG"
		"xpos"			"0"
		"ypos"			"-15"
		"zpos"			"1"
		"wide"			"100"
		"tall"			"110"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../hud/mid_meter"
		"scaleImage"	"1"
	}
	
	"ServerTimeLimitLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"ServerTimeLimitLabel"
		"xpos"			"12"
		"ypos"			"31"
		"ypos_minmode"	"30"
		"zpos"			"5"
		"wide"			"78"
		"tall"			"20"
		"tall_minmode"	"20"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"%servertimeleft%"
		"textAlignment"	"center"
		"font"			"HudFontSmallestBold"
		"fgcolor"		"brightyellow"
		"dropshadow"	"1"
	}
	
	"ServerTimeLimitLabelBG"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"ServerTimeLimitLabelBG"
		"xpos"			"12"
		"ypos"			"29"
		"ypos_minmode"	"28"
		"zpos"			"1"
		"wide"			"78"
		"tall"			"21"
		"tall_minmode"	"21"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../hud/mid_meter"
		"scaleImage"	"1"
	}
}
