"Resource/UI/HudPlayerClass.res"
{
	// player class data
	"HudPlayerClass"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"HudPlayerClass"
		"xpos"			"0"
		"xpos_minmode"	"-20"
		"ypos"			"0"
		"ypos_minmode"	"18"
		"zpos"			"1"
		"wide"			"f0"
		"tall"			"480"
		"visible"		"1"
		"enabled"		"1"		
	}
	"PlayerStatusClassImage"
	{
		"ControlName"	"CTFClassImage"
		"fieldName"		"PlayerStatusClassImage"
		"xpos"			"34"
		"ypos"			"377"
		"zpos"			"2"
		"wide"			"76"
		"tall"			"76"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"
	}
	"PlayerStatusSpyImage"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"PlayerStatusSpyImage"
		"xpos"			"8"
		"ypos"			"385"
		"zpos"			"2"
		"wide"			"68"
		"tall"			"68"
		"visible"		"1"
		"enabled"		"1"
		"image"			"../hud/class/spy_red"
		"scaleImage"	"1"	
		"teambg_2"		"../hud/class/spy_red"
		"teambg_3"		"../hud/class/spy_blue"			
		"teambg_4"		"../hud/class/spy_green"
		"teambg_5"		"../hud/class/spy_yellow"
		
		"drawcolor"		"160 160 160 255"
	}	
	"PlayerStatusSpyOutlineImage"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"PlayerStatusSpyOutlineImage"
		"xpos"			"18"
		"xpos_minmode"	"-5"
		"ypos"			"r87"
		"ypos_minmode"	"r44"
		"zpos"			"3"
		"wide"			"72"
		"wide_minmode"	"27"
		"tall"			"72"
		"tall_minmode"	"27"
		"visible"		"0"
		"enabled"		"1"
		"image"			"../hud/class/spy_outline"
		"scaleImage"	"1"	
	}	
	
	"PlayerStatusClassImageBG"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"PlayerStatusClassImageBG"
		"xpos"			"26"
		"ypos"			"376"
		"zpos"			"1"		
		"wide"			"100"
		"tall"			"100"
		"visible"		"1"
		"enabled"		"1"
		"image"			"../hud/health/health_neu"
		"scaleImage"	"1"
		"teambg_2"		"../hud/health/health_red"
		"teambg_3"		"../hud/health/health_blu"
		"teambg_4"		"../hud/health/health_grn"
		"teambg_5"		"../hud/health/health_ylw"
	}

	"classmodelpanelBG"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"classmodelpanelBG"
		"xpos"			"26"
		"ypos"			"376"
		"zpos"			"1"
		"wide"			"100"
		"tall"			"100"
		"visible"		"1"
		"enabled"		"1"
		"image"			"../hud/health/health_neu"
		"scaleImage"	"1"
		"teambg_2"		"../hud/health/health_red"
		"teambg_3"		"../hud/health/health_blu"
		"teambg_4"		"../hud/health/health_grn"
		"teambg_5"		"../hud/health/health_ylw"
	}
	
	"PlayerStatusClassImageBGContour"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatusClassImageBGContour"
		"pin_to_sibling"	"PlayerStatusClassImageBG"
		"xpos"			"4"
		"ypos"			"-4"
		"zpos"			"1"
		"wide"			"100"
		"tall"			"100"
		"visible"		"1"
		"enabled"		"1"
		"image"			"resource/svgs/health/health_mask.svg"
		"drawcolor" 	"TanLight"
		"scaleImage"	"1"	
	}
	
	"PlayerClassHealthIcon"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerClassHealthIcon"
		"pin_to_sibling"	"PlayerStatusClassImageBG"
		"xpos"			"22"
		"ypos"			"-1"
		"zpos"			"2"
		"wide"			"100"
		"tall"			"100"
		"visible"		"1"
		"enabled"		"1"
		"image"			"resource/svgs/health/health_icon_mask.svg"
		"drawcolor" 	"ContourDark"
		"alpha"			"127.5"
		"scaleImage"	"1"	
	}
	
	"HealthBG"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"HealthBG"
		"xpos"			"68"
		"ypos"			"374"
		"zpos"			"3"
		"wide"					"100"
		"tall"					"100"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"
		"image"			"../hud/health/health_bar/health_bar_outer"
	}
	
	"HealthAboveBGContour"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"HealthAboveBGContour"
		"xpos"			"116"
		"ypos"			"373"
		"zpos"			"2"
		"wide"					"50"
		"tall"					"50"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"
		"image"			"resource/svgs/health/health_bar_outer_upper_mask.svg"
		"drawcolor" 	"TanLight"
	}
	
	"HealthBGContour"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"HealthBGContour"
		"pin_to_sibling" "HealthBG"
		"xpos"			"3"
		"ypos"			"-3"
		"zpos"			"0"
		"wide"					"100"
		"tall"					"100"
		"visible"		"1"
		"enabled"		"1"
		"scaleImage"	"1"
		"drawcolor" 	"TanLight"
		"image"			"resource/svgs/health/health_bar_outer_mask.svg"
	}

	"classmodelpanel"
	{
		"ControlName"	"CTFPlayerModelPanel"
		"fieldName"		"classmodelpanel"
		
		"xpos"			"0"
		"ypos"			"r215"
		"zpos"			"2"		
		"wide"			"140"
		"tall"			"200"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		
		"render_texture"	"0"
		"fov"			"12"
		"allow_rot"		"1"

		"disable_speak_event"	"1"

		"look_at_camera" "0"
				
		"model"
		{
			"force_pos"	"1"

			"angles_x" "0"
			"angles_y" "172"
			"angles_z" "0"
			"origin_x" "200"
			"origin_y" "0"
			"origin_z" "-60"
			"frame_origin_x"	"0"
			"frame_origin_y"	"0"
			"frame_origin_z"	"0"
			"spotlight" "1"
		
			"modelname"		""
		}

		"customclassdata"
		{
			"undefined"
			{
			}
			"Scout"
			{
				"fov"			"35"
				"angles_x"		"-17"
				"angles_y"		"170"
				"angles_z"		"-2"
				"origin_x"		"105"
				"origin_y"		"12"
				"origin_y_minmode"	"24"
				"origin_z"		"-82"
			}
			"Sniper"
			{
				"fov"			"30"
				"angles_x"		"-10"
				"angles_y"		"210"
				"angles_z"		"0"
				"origin_x"		"130"
				"origin_y"		"1"
				"origin_y_minmode"	"14"
				"origin_z"		"-90"
			}
			"Soldier"
			{
				"fov"			"35"
				"angles_x"		"-10"
				"angles_y"		"170"
				"angles_z"		"0"
				"origin_x"		"145"
				"origin_y"		"4"
				"origin_y_minmode"	"16"
				"origin_z"		"-95"
			}
			"Demoman"
			{
				"fov"			"30"
				"angles_x"		"-10"
				"angles_y"		"200"
				"angles_z"		"0"
				"origin_x"		"155"
				"origin_y"		"2"
				"origin_y_minmode"	"14"
				"origin_z"		"-90"
			}
			"Medic"
			{
				"fov"			"30"
				"angles_x"		"-5"
				"angles_y"		"205"
				"angles_z"		"0"
				"origin_x"		"140"
				"origin_y"		"3"
				"origin_y_minmode"	"15"
				"origin_z"		"-90"
			}
			"Heavy"
			{
				"fov"			"30"
				"angles_x"		"-4"
				"angles_y"		"210"
				"angles_z"		"-1"
				"origin_x"		"190"
				"origin_y"		"6"
				"origin_y_minmode"	"18"
				"origin_z"		"-100"
			}
			"Pyro"
			{
				"fov"			"30"
				"angles_x"		"-5"
				"angles_y"		"195"
				"angles_z"		"0"
				"origin_x"		"155"
				"origin_y"		"6"
				"origin_y_minmode"	"18"
				"origin_z"		"-85"
			}
			"Spy"
			{
				"fov"			"30"
				"angles_x"		"-5"
				"angles_y"		"200"
				"angles_z"		"0"
				"origin_x"		"140"
				"origin_y"		"5"
				"origin_y_minmode"	"17"
				"origin_z"		"-90"
			}
			"Engineer"
			{
				"fov"			"30"
				"angles_x"		"-10"
				"angles_y"		"200"
				"angles_z"		"-3"
				"origin_x"		"140"
				"origin_y"		"6"
				"origin_y_minmode"	"16"
				"origin_z"		"-82"
			}
			"Civilian"
			{
				"fov"			"30"
				"angles_x"		"-10"
				"angles_y"		"168"
				"angles_z"		"0"
				"origin_x"		"140"
				"origin_y"		"7"
				"origin_y_minmode"	"19"
				"origin_z"		"-78"
			}
		}
	}

	"CarryingWeapon"
	{
		"ControlName"			"EditablePanel"
		"fieldName"				"CarryingWeapon"
		"xpos"					"20"
		"xpos_minmode"			"90"
		"ypos"					"r27"
		"ypos_minmode"			"r36"
		"zpos"					"100"
		"wide"					"500"
		"wide_minmode"			"500"
		"tall"	 				"28"
		"tall_minmode"	 		"28"

		"CarryingBackground"
		{
			"ControlName"			"CTFImagePanel"
			"fieldName"				"CarryingBackground"
			"xpos"					"0"
			"xpos_minmode"			"0"
			"ypos"					"0"
			"ypos_minmode"			"0"
			"zpos"					"0"
			"wide"					"p1"
			"wide_minmode"			"f0"
			"tall"	 				"f0"
			"tall_minmode"			"f0"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"image"					"../hud/color_panel_brown"
			"scaleImage"			"1"
			"teambg_1"				"../hud/color_panel_brown"
			"teambg_2"				"../hud/color_panel_red"
			"teambg_2_lodef"		"../hud/color_panel_red"
			"teambg_3"				"../hud/color_panel_blu"
			"teambg_3_lodef"		"../hud/color_panel_blu"
			"teambg_4"				"../hud/color_panel_grn"
			"teambg_4_lodef"		"../hud/color_panel_grn"
			"teambg_5"				"../hud/color_panel_ylw"
			"teambg_5_lodef"		"../hud/color_panel_ylw"
			"proportionaltoparent"	"1"
		
			"src_corner_height"		"23"				// pixels inside the image
			"src_corner_width"		"23"
			
			"draw_corner_width"		"5"				// screen size of the corners ( and sides ), proportional
			"draw_corner_height" 	"5"	
		}

		"CarryingLabel"
		{	
			"ControlName"		"CExLabel"
			"fieldName"			"CarryingLabel"
			"font"				"ReplayBrowserSmallest"
			"font_minmode"		"TFFontMedium"
			"xpos"				"5"
			"xpos_minmode"		"5"
			"ypos"				"3"
			"ypos_minmode"		"2"
			"zpos"				"1"
			"wide"				"200"
			"wide_minmode"		"f0"
			"tall"	 			"f0"
			"tall_minmode"		"f0"
			"autoResize"		"0"
			"pinCorner"			"0"
			"visible"			"1"
			"enabled"			"1"
			"textAlignment"		"North-West"
			"dulltext"			"0"
			"brighttext"		"0"
			"proportionaltoparent"	"1"
			"auto_wide_tocontents"	"1"
			"labelText"			"%carrying%"
		}

		"CarryingLabelDropShadow"
		{	
			"ControlName"		"CExLabel"
			"fieldName"			"CarryingLabelDropShadow"
			"font"				"ReplayBrowserSmallest"
			"font_minmode"		"TFFontMedium"
			"xpos"				"p0.011"
			"xpos_minmode"		"6"
			"ypos"				"p0.12"
			"ypos_minmode"		"3"
			"zpos"				"0"
			"wide"				"200"
			"wide_minmode"		"f0"
			"tall"	 			"f0"
			"tall_minmode"		"f0"
			"autoResize"		"0"
			"pinCorner"			"0"
			"visible"			"1"
			"enabled"			"1"
			"textAlignment"		"North-West"
			"dulltext"			"0"
			"brighttext"		"0"
			"proportionaltoparent"	"1"
			"auto_wide_tocontents"	"1"
			"fgcolor_override"	"Black"
			"labelText"			"%carrying%"
		}

		"OwnerLabel"
		{	
			"ControlName"		"Label"
			"fieldName"			"OwnerLabel"
			"font"				"FontStoreOriginalPrice"
			"font_minmode"		"TFFontSmall"
			"xpos"				"5"
			"xpos_minmode"		"5"
			"ypos"				"12"
			"ypos_minmode"		"10"
			"zpos"				"0"
			"wide"				"200"
			"wide_minmode"		"f0"
			"tall"	 			"f0"
			"tall_minmode"		"f0"
			"autoResize"		"0"
			"pinCorner"			"0"
			"visible"			"1"
			"enabled"			"1"
			"textAlignment"		"North-West"
			"dulltext"			"0"
			"brighttext"		"0"
			"proportionaltoparent"	"1"
			"auto_wide_tocontents"	"1"
		}
	}
}
